// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package renovate

type Config struct {
	// Flags packages that have not been updated within this period as abandoned.
	AbandonmentThreshold *string `json:"abandonmentThreshold,omitempty" yaml:"abandonmentThreshold,omitempty" mapstructure:"abandonmentThreshold,omitempty"`

	// Labels to add to Pull Request.
	AddLabels []string `json:"addLabels,omitempty" yaml:"addLabels,omitempty" mapstructure:"addLabels,omitempty"`

	// Additional string value to be appended to `branchPrefix`.
	AdditionalBranchPrefix string `json:"additionalBranchPrefix,omitempty" yaml:"additionalBranchPrefix,omitempty" mapstructure:"additionalBranchPrefix,omitempty"`

	// Additional reviewers for Pull Requests (in contrast to `reviewers`, this option
	// adds to the existing reviewer list, rather than replacing it).
	AdditionalReviewers []string `json:"additionalReviewers,omitempty" yaml:"additionalReviewers,omitempty" mapstructure:"additionalReviewers,omitempty"`

	// Assign reviewers and assignees even if the PR is to be automerged.
	AssignAutomerge bool `json:"assignAutomerge,omitempty" yaml:"assignAutomerge,omitempty" mapstructure:"assignAutomerge,omitempty"`

	// Assignees for Pull Request (either username or email address depending on the
	// platform).
	Assignees []string `json:"assignees,omitempty" yaml:"assignees,omitempty" mapstructure:"assignees,omitempty"`

	// Determine assignees based on configured code owners and changes in PR.
	AssigneesFromCodeOwners bool `json:"assigneesFromCodeOwners,omitempty" yaml:"assigneesFromCodeOwners,omitempty" mapstructure:"assigneesFromCodeOwners,omitempty"`

	// Take a random sample of given size from `assignees`.
	AssigneesSampleSize *int `json:"assigneesSampleSize,omitempty" yaml:"assigneesSampleSize,omitempty" mapstructure:"assigneesSampleSize,omitempty"`

	// Set to `true` to automatically approve PRs.
	AutoApprove bool `json:"autoApprove,omitempty" yaml:"autoApprove,omitempty" mapstructure:"autoApprove,omitempty"`

	// Control whether replacement regular expressions are global matches or only the
	// first match.
	AutoReplaceGlobalMatch bool `json:"autoReplaceGlobalMatch,omitempty" yaml:"autoReplaceGlobalMatch,omitempty" mapstructure:"autoReplaceGlobalMatch,omitempty"`

	// Whether to automerge branches/PRs automatically, without human intervention.
	Automerge bool `json:"automerge,omitempty" yaml:"automerge,omitempty" mapstructure:"automerge,omitempty"`

	// PR comment to add to trigger automerge. Only used if
	// `automergeType=pr-comment`.
	AutomergeComment string `json:"automergeComment,omitempty" yaml:"automergeComment,omitempty" mapstructure:"automergeComment,omitempty"`

	// Limit automerge to these times of day or week.
	AutomergeSchedule interface{} `json:"automergeSchedule,omitempty" yaml:"automergeSchedule,omitempty" mapstructure:"automergeSchedule,omitempty"`

	// The merge strategy to use when automerging PRs. Used only if
	// `automergeType=pr`.
	AutomergeStrategy ConfigAutomergeStrategy `json:"automergeStrategy,omitempty" yaml:"automergeStrategy,omitempty" mapstructure:"automergeStrategy,omitempty"`

	// How to automerge, if enabled.
	AutomergeType ConfigAutomergeType `json:"automergeType,omitempty" yaml:"automergeType,omitempty" mapstructure:"automergeType,omitempty"`

	// The id of an existing work item on Azure Boards to link to each PR.
	AzureWorkItemId int `json:"azureWorkItemId,omitempty" yaml:"azureWorkItemId,omitempty" mapstructure:"azureWorkItemId,omitempty"`

	// List of one or more custom base branches defined as exact strings and/or via
	// regex expressions.
	BaseBranchPatterns []string `json:"baseBranchPatterns,omitempty" yaml:"baseBranchPatterns,omitempty" mapstructure:"baseBranchPatterns,omitempty"`

	// The PR tasks will be automatically completed after the PR is raised.
	BbAutoResolvePrTasks bool `json:"bbAutoResolvePrTasks,omitempty" yaml:"bbAutoResolvePrTasks,omitempty" mapstructure:"bbAutoResolvePrTasks,omitempty"`

	// Use the default reviewers (Bitbucket only).
	BbUseDefaultReviewers bool `json:"bbUseDefaultReviewers,omitempty" yaml:"bbUseDefaultReviewers,omitempty" mapstructure:"bbUseDefaultReviewers,omitempty"`

	// Limit to a maximum of x concurrent branches. 0 means no limit, `null` (default)
	// inherits value from `prConcurrentLimit`.
	BranchConcurrentLimit *int `json:"branchConcurrentLimit,omitempty" yaml:"branchConcurrentLimit,omitempty" mapstructure:"branchConcurrentLimit,omitempty"`

	// Branch name template.
	BranchName string `json:"branchName,omitempty" yaml:"branchName,omitempty" mapstructure:"branchName,omitempty"`

	// Whether to be strict about the use of special characters within the branch
	// name.
	BranchNameStrict bool `json:"branchNameStrict,omitempty" yaml:"branchNameStrict,omitempty" mapstructure:"branchNameStrict,omitempty"`

	// Prefix to use for all branch names.
	BranchPrefix string `json:"branchPrefix,omitempty" yaml:"branchPrefix,omitempty" mapstructure:"branchPrefix,omitempty"`

	// Old branchPrefix value to check for existing PRs.
	BranchPrefixOld string `json:"branchPrefixOld,omitempty" yaml:"branchPrefixOld,omitempty" mapstructure:"branchPrefixOld,omitempty"`

	// Branch topic.
	BranchTopic string `json:"branchTopic,omitempty" yaml:"branchTopic,omitempty" mapstructure:"branchTopic,omitempty"`

	// Bump the version in the package file being updated.
	BumpVersion *ConfigBumpVersion `json:"bumpVersion,omitempty" yaml:"bumpVersion,omitempty" mapstructure:"bumpVersion,omitempty"`

	// A list of bumpVersion config options to bump generic version numbers.
	BumpVersions []interface{} `json:"bumpVersions,omitempty" yaml:"bumpVersions,omitempty" mapstructure:"bumpVersions,omitempty"`

	// Set to `true` to initialize submodules during repository clone.
	CloneSubmodules bool `json:"cloneSubmodules,omitempty" yaml:"cloneSubmodules,omitempty" mapstructure:"cloneSubmodules,omitempty"`

	// List of submodules names or patterns to clone when cloneSubmodules=true.
	CloneSubmodulesFilter []string `json:"cloneSubmodulesFilter,omitempty" yaml:"cloneSubmodulesFilter,omitempty" mapstructure:"cloneSubmodulesFilter,omitempty"`

	// Commit message body template. Will be appended to commit message, separated by
	// two line returns.
	CommitBody *string `json:"commitBody,omitempty" yaml:"commitBody,omitempty" mapstructure:"commitBody,omitempty"`

	// If enabled, append a table in the commit message body describing all updates in
	// the commit.
	CommitBodyTable bool `json:"commitBodyTable,omitempty" yaml:"commitBodyTable,omitempty" mapstructure:"commitBodyTable,omitempty"`

	// Message to use for commit messages and pull request titles.
	CommitMessage string `json:"commitMessage,omitempty" yaml:"commitMessage,omitempty" mapstructure:"commitMessage,omitempty"`

	// Action verb to use in commit messages and PR titles.
	CommitMessageAction string `json:"commitMessageAction,omitempty" yaml:"commitMessageAction,omitempty" mapstructure:"commitMessageAction,omitempty"`

	// Extra description used after the commit message topic - typically the version.
	CommitMessageExtra string `json:"commitMessageExtra,omitempty" yaml:"commitMessageExtra,omitempty" mapstructure:"commitMessageExtra,omitempty"`

	// Lowercase PR- and commit titles.
	CommitMessageLowerCase ConfigCommitMessageLowerCase `json:"commitMessageLowerCase,omitempty" yaml:"commitMessageLowerCase,omitempty" mapstructure:"commitMessageLowerCase,omitempty"`

	// Prefix to add to start of commit messages and PR titles. Uses a semantic prefix
	// if `semanticCommits` is enabled.
	CommitMessagePrefix *string `json:"commitMessagePrefix,omitempty" yaml:"commitMessagePrefix,omitempty" mapstructure:"commitMessagePrefix,omitempty"`

	// Suffix to add to end of commit messages and PR titles.
	CommitMessageSuffix *string `json:"commitMessageSuffix,omitempty" yaml:"commitMessageSuffix,omitempty" mapstructure:"commitMessageSuffix,omitempty"`

	// The upgrade topic/noun used in commit messages and PR titles.
	CommitMessageTopic string `json:"commitMessageTopic,omitempty" yaml:"commitMessageTopic,omitempty" mapstructure:"commitMessageTopic,omitempty"`

	// Configure use of `--ignore-platform-reqs` or `--ignore-platform-req` for the
	// Composer package manager.
	ComposerIgnorePlatformReqs []string `json:"composerIgnorePlatformReqs,omitempty" yaml:"composerIgnorePlatformReqs,omitempty" mapstructure:"composerIgnorePlatformReqs,omitempty"`

	// If enabled, issues created by Renovate are set as confidential.
	Confidential bool `json:"confidential,omitempty" yaml:"confidential,omitempty" mapstructure:"confidential,omitempty"`

	// Enable this to get config migration PRs when needed.
	ConfigMigration bool `json:"configMigration,omitempty" yaml:"configMigration,omitempty" mapstructure:"configMigration,omitempty"`

	// Set this to `true` to make Renovate reuse/reopen an existing closed Config
	// Warning issue, instead of opening a new one each time.
	ConfigWarningReuseIssue bool `json:"configWarningReuseIssue,omitempty" yaml:"configWarningReuseIssue,omitempty" mapstructure:"configWarningReuseIssue,omitempty"`

	// Configuration object to define language or manager version constraints.
	Constraints ConfigConstraints `json:"constraints,omitempty" yaml:"constraints,omitempty" mapstructure:"constraints,omitempty"`

	// Perform release filtering based on language constraints.
	ConstraintsFiltering ConfigConstraintsFiltering `json:"constraintsFiltering,omitempty" yaml:"constraintsFiltering,omitempty" mapstructure:"constraintsFiltering,omitempty"`

	// Custom managers using regex matching.
	CustomManagers []interface{} `json:"customManagers,omitempty" yaml:"customManagers,omitempty" mapstructure:"customManagers,omitempty"`

	// Customize sections in the Dependency Dashboard issue.
	CustomizeDashboard ConfigCustomizeDashboard `json:"customizeDashboard,omitempty" yaml:"customizeDashboard,omitempty" mapstructure:"customizeDashboard,omitempty"`

	// List of registry URLs to use as the default for a datasource.
	DefaultRegistryUrls []string `json:"defaultRegistryUrls,omitempty" yaml:"defaultRegistryUrls,omitempty" mapstructure:"defaultRegistryUrls,omitempty"`

	// Whether to create a "Dependency Dashboard" issue in the repository.
	DependencyDashboard bool `json:"dependencyDashboard,omitempty" yaml:"dependencyDashboard,omitempty" mapstructure:"dependencyDashboard,omitempty"`

	// Controls if updates need manual approval from the Dependency Dashboard issue
	// before PRs are created.
	DependencyDashboardApproval bool `json:"dependencyDashboardApproval,omitempty" yaml:"dependencyDashboardApproval,omitempty" mapstructure:"dependencyDashboardApproval,omitempty"`

	// Set to `true` to let Renovate close the Dependency Dashboard issue if there are
	// no more updates.
	DependencyDashboardAutoclose bool `json:"dependencyDashboardAutoclose,omitempty" yaml:"dependencyDashboardAutoclose,omitempty" mapstructure:"dependencyDashboardAutoclose,omitempty"`

	// The category to group branches on the Dependency Dashboard issue.
	DependencyDashboardCategory *string `json:"dependencyDashboardCategory,omitempty" yaml:"dependencyDashboardCategory,omitempty" mapstructure:"dependencyDashboardCategory,omitempty"`

	// Any text added here will be placed last in the Dependency Dashboard issue body,
	// with a divider separator before it.
	DependencyDashboardFooter *string `json:"dependencyDashboardFooter,omitempty" yaml:"dependencyDashboardFooter,omitempty" mapstructure:"dependencyDashboardFooter,omitempty"`

	// Any text added here will be placed first in the Dependency Dashboard issue
	// body.
	DependencyDashboardHeader string `json:"dependencyDashboardHeader,omitempty" yaml:"dependencyDashboardHeader,omitempty" mapstructure:"dependencyDashboardHeader,omitempty"`

	// These labels will always be applied on the Dependency Dashboard issue, even
	// when they have been removed manually.
	DependencyDashboardLabels []string `json:"dependencyDashboardLabels,omitempty" yaml:"dependencyDashboardLabels,omitempty" mapstructure:"dependencyDashboardLabels,omitempty"`

	// Control if the Dependency Dashboard issue lists CVEs supplied by
	// [osv.dev](https://osv.dev).
	DependencyDashboardOSVVulnerabilitySummary ConfigDependencyDashboardOSVVulnerabilitySummary `json:"dependencyDashboardOSVVulnerabilitySummary,omitempty" yaml:"dependencyDashboardOSVVulnerabilitySummary,omitempty" mapstructure:"dependencyDashboardOSVVulnerabilitySummary,omitempty"`

	// Controls whether abandoned packages are reported in the dependency dashboard.
	DependencyDashboardReportAbandonment bool `json:"dependencyDashboardReportAbandonment,omitempty" yaml:"dependencyDashboardReportAbandonment,omitempty" mapstructure:"dependencyDashboardReportAbandonment,omitempty"`

	// Title for the Dependency Dashboard issue.
	DependencyDashboardTitle string `json:"dependencyDashboardTitle,omitempty" yaml:"dependencyDashboardTitle,omitempty" mapstructure:"dependencyDashboardTitle,omitempty"`

	// Plain text description for a config or preset.
	Description interface{} `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// If set to `true` then Renovate creates draft PRs, instead of normal status PRs.
	DraftPR bool `json:"draftPR,omitempty" yaml:"draftPR,omitempty" mapstructure:"draftPR,omitempty"`

	// Enable or disable corresponding functionality.
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// A list of package managers to enable. Only managers on the list are enabled.
	EnabledManagers []string `json:"enabledManagers,omitempty" yaml:"enabledManagers,omitempty" mapstructure:"enabledManagers,omitempty"`

	// A file matching any of these glob patterns will not be committed, even if the
	// file has been updated.
	ExcludeCommitPaths []string `json:"excludeCommitPaths,omitempty" yaml:"excludeCommitPaths,omitempty" mapstructure:"excludeCommitPaths,omitempty"`

	// Expand the configured code owner groups into a full list of group members.
	ExpandCodeOwnersGroups bool `json:"expandCodeOwnersGroups,omitempty" yaml:"expandCodeOwnersGroups,omitempty" mapstructure:"expandCodeOwnersGroups,omitempty"`

	// Configuration presets to use or extend.
	Extends interface{} `json:"extends,omitempty" yaml:"extends,omitempty" mapstructure:"extends,omitempty"`

	// A regex (`re2`) to extract a version from a datasource's raw version string.
	ExtractVersion *string `json:"extractVersion,omitempty" yaml:"extractVersion,omitempty" mapstructure:"extractVersion,omitempty"`

	// Controls if and when changelogs/release notes are fetched.
	FetchChangeLogs ConfigFetchChangeLogs `json:"fetchChangeLogs,omitempty" yaml:"fetchChangeLogs,omitempty" mapstructure:"fetchChangeLogs,omitempty"`

	// Filter reviewers and assignees based on their availability.
	FilterUnavailableUsers bool `json:"filterUnavailableUsers,omitempty" yaml:"filterUnavailableUsers,omitempty" mapstructure:"filterUnavailableUsers,omitempty"`

	// If defined, packages will follow this release tag exactly.
	FollowTag *string `json:"followTag,omitempty" yaml:"followTag,omitempty" mapstructure:"followTag,omitempty"`

	// Disallow maintainers to push to Renovate pull requests when running in fork
	// mode.
	ForkModeDisallowMaintainerEdits bool `json:"forkModeDisallowMaintainerEdits,omitempty" yaml:"forkModeDisallowMaintainerEdits,omitempty" mapstructure:"forkModeDisallowMaintainerEdits,omitempty"`

	// Whether to process forked repositories. By default, all forked repositories are
	// skipped when in `autodiscover` mode.
	ForkProcessing ConfigForkProcessing `json:"forkProcessing,omitempty" yaml:"forkProcessing,omitempty" mapstructure:"forkProcessing,omitempty"`

	// Author to use for Git commits. Must conform to
	// [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322).
	GitAuthor *string `json:"gitAuthor,omitempty" yaml:"gitAuthor,omitempty" mapstructure:"gitAuthor,omitempty"`

	// Git authors which are ignored by Renovate. Must conform to
	// [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322).
	GitIgnoredAuthors []string `json:"gitIgnoredAuthors,omitempty" yaml:"gitIgnoredAuthors,omitempty" mapstructure:"gitIgnoredAuthors,omitempty"`

	// Ignore approval rules for MRs created by Renovate, which is useful for
	// automerge.
	GitLabIgnoreApprovals bool `json:"gitLabIgnoreApprovals,omitempty" yaml:"gitLabIgnoreApprovals,omitempty" mapstructure:"gitLabIgnoreApprovals,omitempty"`

	// Directory pattern to run `go get` on.
	GoGetDirs []string `json:"goGetDirs,omitempty" yaml:"goGetDirs,omitempty" mapstructure:"goGetDirs,omitempty"`

	// Human understandable name for the dependency group.
	GroupName *string `json:"groupName,omitempty" yaml:"groupName,omitempty" mapstructure:"groupName,omitempty"`

	// Slug to use for group (e.g. in branch name). Slug is calculated from
	// `groupName` if `null`.
	GroupSlug *string `json:"groupSlug,omitempty" yaml:"groupSlug,omitempty" mapstructure:"groupSlug,omitempty"`

	// If enabled, branch names will use a hashing function to ensure each branch has
	// that length.
	HashedBranchLength *int `json:"hashedBranchLength,omitempty" yaml:"hashedBranchLength,omitempty" mapstructure:"hashedBranchLength,omitempty"`

	// Host rules/configuration including credentials.
	HostRules []interface{} `json:"hostRules,omitempty" yaml:"hostRules,omitempty" mapstructure:"hostRules,omitempty"`

	// Avoid upgrading from a non-deprecated version to a deprecated one.
	IgnoreDeprecated bool `json:"ignoreDeprecated,omitempty" yaml:"ignoreDeprecated,omitempty" mapstructure:"ignoreDeprecated,omitempty"`

	// Dependencies to ignore.
	IgnoreDeps []string `json:"ignoreDeps,omitempty" yaml:"ignoreDeps,omitempty" mapstructure:"ignoreDeps,omitempty"`

	// Skip any package file whose path matches one of these. Can be a string or glob
	// pattern.
	IgnorePaths []string `json:"ignorePaths,omitempty" yaml:"ignorePaths,omitempty" mapstructure:"ignorePaths,omitempty"`

	// Set this to `true` if `allowPlugins=true` but you wish to skip running plugins
	// when updating lock files.
	IgnorePlugins bool `json:"ignorePlugins,omitempty" yaml:"ignorePlugins,omitempty" mapstructure:"ignorePlugins,omitempty"`

	// A list of presets to ignore, including any that are nested inside an `extends`
	// array.
	IgnorePresets interface{} `json:"ignorePresets,omitempty" yaml:"ignorePresets,omitempty" mapstructure:"ignorePresets,omitempty"`

	// Reviewers to be ignored in PR reviewers presence (either username or email
	// address depending on the platform).
	IgnoreReviewers []string `json:"ignoreReviewers,omitempty" yaml:"ignoreReviewers,omitempty" mapstructure:"ignoreReviewers,omitempty"`

	// Set this to `false` if `allowScripts=true` and you wish to run scripts when
	// updating lock files.
	IgnoreScripts bool `json:"ignoreScripts,omitempty" yaml:"ignoreScripts,omitempty" mapstructure:"ignoreScripts,omitempty"`

	// Set to `true` to enable automerging without tests.
	IgnoreTests bool `json:"ignoreTests,omitempty" yaml:"ignoreTests,omitempty" mapstructure:"ignoreTests,omitempty"`

	// Ignore versions with unstable SemVer.
	IgnoreUnstable bool `json:"ignoreUnstable,omitempty" yaml:"ignoreUnstable,omitempty" mapstructure:"ignoreUnstable,omitempty"`

	// Include package files only within these defined paths.
	IncludePaths []string `json:"includePaths,omitempty" yaml:"includePaths,omitempty" mapstructure:"includePaths,omitempty"`

	// Whether to consider passing internal checks such as `minimumReleaseAge` when
	// determining branch status.
	InternalChecksAsSuccess bool `json:"internalChecksAsSuccess,omitempty" yaml:"internalChecksAsSuccess,omitempty" mapstructure:"internalChecksAsSuccess,omitempty"`

	// When and how to filter based on internal checks.
	InternalChecksFilter ConfigInternalChecksFilter `json:"internalChecksFilter,omitempty" yaml:"internalChecksFilter,omitempty" mapstructure:"internalChecksFilter,omitempty"`

	// If set, users can add this label to PRs to request they be kept updated with
	// the base branch.
	KeepUpdatedLabel *string `json:"keepUpdatedLabel,omitempty" yaml:"keepUpdatedLabel,omitempty" mapstructure:"keepUpdatedLabel,omitempty"`

	// Labels to set in Pull Request.
	Labels []string `json:"labels,omitempty" yaml:"labels,omitempty" mapstructure:"labels,omitempty"`

	// Remap log levels to different levels.
	LogLevelRemap []interface{} `json:"logLevelRemap,omitempty" yaml:"logLevelRemap,omitempty" mapstructure:"logLevelRemap,omitempty"`

	// Limit the maximum major version increment allowed. Set to 0 to disable.
	MaxMajorIncrement int `json:"maxMajorIncrement,omitempty" yaml:"maxMajorIncrement,omitempty" mapstructure:"maxMajorIncrement,omitempty"`

	// The number of a milestone. If set, the milestone will be set when Renovate
	// creates the PR.
	Milestone *int `json:"milestone,omitempty" yaml:"milestone,omitempty" mapstructure:"milestone,omitempty"`

	// The minimum number of updates which must be in a group for branches to be
	// created.
	MinimumGroupSize int `json:"minimumGroupSize,omitempty" yaml:"minimumGroupSize,omitempty" mapstructure:"minimumGroupSize,omitempty"`

	// Time required before a new release is considered stable.
	MinimumReleaseAge *string `json:"minimumReleaseAge,omitempty" yaml:"minimumReleaseAge,omitempty" mapstructure:"minimumReleaseAge,omitempty"`

	// When set in conjunction with `minimumReleaseAge`, controls whether the
	// `releaseTimestamp` for a dependency update is required.
	MinimumReleaseAgeBehaviour ConfigMinimumReleaseAgeBehaviour `json:"minimumReleaseAgeBehaviour,omitempty" yaml:"minimumReleaseAgeBehaviour,omitempty" mapstructure:"minimumReleaseAgeBehaviour,omitempty"`

	// Mode of operation.
	Mode ConfigMode `json:"mode,omitempty" yaml:"mode,omitempty" mapstructure:"mode,omitempty"`

	// npm token used to authenticate with the default registry.
	NpmToken *string `json:"npmToken,omitempty" yaml:"npmToken,omitempty" mapstructure:"npmToken,omitempty"`

	// String copy of `.npmrc` file. Use `\n` instead of line breaks.
	Npmrc *string `json:"npmrc,omitempty" yaml:"npmrc,omitempty" mapstructure:"npmrc,omitempty"`

	// Whether to merge `config.npmrc` with repo `.npmrc` content if both are found.
	NpmrcMerge bool `json:"npmrcMerge,omitempty" yaml:"npmrcMerge,omitempty" mapstructure:"npmrcMerge,omitempty"`

	// Use vulnerability alerts from `osv.dev`.
	OsvVulnerabilityAlerts bool `json:"osvVulnerabilityAlerts,omitempty" yaml:"osvVulnerabilityAlerts,omitempty" mapstructure:"osvVulnerabilityAlerts,omitempty"`

	// Rules for matching packages.
	PackageRules []interface{} `json:"packageRules,omitempty" yaml:"packageRules,omitempty" mapstructure:"packageRules,omitempty"`

	// Whether to add digests to Dockerfile source images.
	PinDigests bool `json:"pinDigests,omitempty" yaml:"pinDigests,omitempty" mapstructure:"pinDigests,omitempty"`

	// Controls if platform-native auto-merge is used.
	PlatformAutomerge bool `json:"platformAutomerge,omitempty" yaml:"platformAutomerge,omitempty" mapstructure:"platformAutomerge,omitempty"`

	// Use platform API to perform commits instead of using Git directly.
	PlatformCommit ConfigPlatformCommit `json:"platformCommit,omitempty" yaml:"platformCommit,omitempty" mapstructure:"platformCommit,omitempty"`

	// Enable post-update options to be run after package/artifact updating.
	PostUpdateOptions []ConfigPostUpdateOptionsElem `json:"postUpdateOptions,omitempty" yaml:"postUpdateOptions,omitempty" mapstructure:"postUpdateOptions,omitempty"`

	// List of columns to use in PR bodies.
	PrBodyColumns []string `json:"prBodyColumns,omitempty" yaml:"prBodyColumns,omitempty" mapstructure:"prBodyColumns,omitempty"`

	// Table column definitions to use in PR tables.
	PrBodyDefinitions ConfigPrBodyDefinitions `json:"prBodyDefinitions,omitempty" yaml:"prBodyDefinitions,omitempty" mapstructure:"prBodyDefinitions,omitempty"`

	// Table header definitions to use in PR tables.
	PrBodyHeadingDefinitions ConfigPrBodyHeadingDefinitions `json:"prBodyHeadingDefinitions,omitempty" yaml:"prBodyHeadingDefinitions,omitempty" mapstructure:"prBodyHeadingDefinitions,omitempty"`

	// List of extra notes or templates to include in the Pull Request body.
	PrBodyNotes interface{} `json:"prBodyNotes,omitempty" yaml:"prBodyNotes,omitempty" mapstructure:"prBodyNotes,omitempty"`

	// Pull Request body template. Controls which sections are rendered in the body of
	// the pull request.
	PrBodyTemplate string `json:"prBodyTemplate,omitempty" yaml:"prBodyTemplate,omitempty" mapstructure:"prBodyTemplate,omitempty"`

	// Limit to a maximum of x concurrent branches/PRs. 0 means no limit.
	PrConcurrentLimit int `json:"prConcurrentLimit,omitempty" yaml:"prConcurrentLimit,omitempty" mapstructure:"prConcurrentLimit,omitempty"`

	// When to create the PR for a branch.
	PrCreation ConfigPrCreation `json:"prCreation,omitempty" yaml:"prCreation,omitempty" mapstructure:"prCreation,omitempty"`

	// Text added here will be placed last in the PR body, with a divider separator
	// before it.
	PrFooter string `json:"prFooter,omitempty" yaml:"prFooter,omitempty" mapstructure:"prFooter,omitempty"`

	// Text added here will be placed first in the PR body.
	PrHeader *string `json:"prHeader,omitempty" yaml:"prHeader,omitempty" mapstructure:"prHeader,omitempty"`

	// Rate limit PRs to maximum x created per hour. 0 means no limit.
	PrHourlyLimit int `json:"prHourlyLimit,omitempty" yaml:"prHourlyLimit,omitempty" mapstructure:"prHourlyLimit,omitempty"`

	// Timeout in hours for when `prCreation=not-pending`.
	PrNotPendingHours int `json:"prNotPendingHours,omitempty" yaml:"prNotPendingHours,omitempty" mapstructure:"prNotPendingHours,omitempty"`

	// Pull Request title template. Inherits from `commitMessage` if null.
	PrTitle *string `json:"prTitle,omitempty" yaml:"prTitle,omitempty" mapstructure:"prTitle,omitempty"`

	// Whether to bypass appending extra context to the Pull Request title.
	PrTitleStrict bool `json:"prTitleStrict,omitempty" yaml:"prTitleStrict,omitempty" mapstructure:"prTitleStrict,omitempty"`

	// If enabled, Renovate logs the fully resolved config for each repository, plus
	// the fully resolved presets.
	PrintConfig bool `json:"printConfig,omitempty" yaml:"printConfig,omitempty" mapstructure:"printConfig,omitempty"`

	// Set to `true` to enable branch pruning after automerging.
	PruneBranchAfterAutomerge bool `json:"pruneBranchAfterAutomerge,omitempty" yaml:"pruneBranchAfterAutomerge,omitempty" mapstructure:"pruneBranchAfterAutomerge,omitempty"`

	// Set to `false` to disable pruning stale branches.
	PruneStaleBranches bool `json:"pruneStaleBranches,omitempty" yaml:"pruneStaleBranches,omitempty" mapstructure:"pruneStaleBranches,omitempty"`

	// Determines how to modify or update existing ranges.
	RangeStrategy ConfigRangeStrategy `json:"rangeStrategy,omitempty" yaml:"rangeStrategy,omitempty" mapstructure:"rangeStrategy,omitempty"`

	// Label to request a rebase from Renovate bot.
	RebaseLabel string `json:"rebaseLabel,omitempty" yaml:"rebaseLabel,omitempty" mapstructure:"rebaseLabel,omitempty"`

	// Controls when Renovate rebases an existing branch.
	RebaseWhen ConfigRebaseWhen `json:"rebaseWhen,omitempty" yaml:"rebaseWhen,omitempty" mapstructure:"rebaseWhen,omitempty"`

	// Recreate PRs even if same ones were closed previously.
	RecreateWhen ConfigRecreateWhen `json:"recreateWhen,omitempty" yaml:"recreateWhen,omitempty" mapstructure:"recreateWhen,omitempty"`

	// List of URLs to try for dependency lookup. Package manager specific.
	RegistryUrls []string `json:"registryUrls,omitempty" yaml:"registryUrls,omitempty" mapstructure:"registryUrls,omitempty"`

	// Select whether to perform a direct replacement or alias replacement.
	ReplacementApproach ConfigReplacementApproach `json:"replacementApproach,omitempty" yaml:"replacementApproach,omitempty" mapstructure:"replacementApproach,omitempty"`

	// Ignore versions newer than npm "latest" version.
	RespectLatest bool `json:"respectLatest,omitempty" yaml:"respectLatest,omitempty" mapstructure:"respectLatest,omitempty"`

	// Requested reviewers for Pull Requests (either username or email address
	// depending on the platform).
	Reviewers []string `json:"reviewers,omitempty" yaml:"reviewers,omitempty" mapstructure:"reviewers,omitempty"`

	// Determine reviewers based on configured code owners and changes in PR.
	ReviewersFromCodeOwners bool `json:"reviewersFromCodeOwners,omitempty" yaml:"reviewersFromCodeOwners,omitempty" mapstructure:"reviewersFromCodeOwners,omitempty"`

	// Take a random sample of given size from `reviewers`.
	ReviewersSampleSize *int `json:"reviewersSampleSize,omitempty" yaml:"reviewersSampleSize,omitempty" mapstructure:"reviewersSampleSize,omitempty"`

	// Create PRs to roll back versions if the current version is not found in the
	// registry.
	RollbackPrs bool `json:"rollbackPrs,omitempty" yaml:"rollbackPrs,omitempty" mapstructure:"rollbackPrs,omitempty"`

	// Limit branch creation to these times of day or week.
	Schedule interface{} `json:"schedule,omitempty" yaml:"schedule,omitempty" mapstructure:"schedule,omitempty"`

	// Commit scope to use if Semantic Commits are enabled.
	SemanticCommitScope string `json:"semanticCommitScope,omitempty" yaml:"semanticCommitScope,omitempty" mapstructure:"semanticCommitScope,omitempty"`

	// Commit type to use if Semantic Commits is enabled.
	SemanticCommitType string `json:"semanticCommitType,omitempty" yaml:"semanticCommitType,omitempty" mapstructure:"semanticCommitType,omitempty"`

	// Enable Semantic Commit prefixes for commits and PR titles.
	SemanticCommits ConfigSemanticCommits `json:"semanticCommits,omitempty" yaml:"semanticCommits,omitempty" mapstructure:"semanticCommits,omitempty"`

	// If set to `false`, Renovate will upgrade dependencies to their latest release
	// only. Renovate will not separate major or minor branches.
	SeparateMajorMinor bool `json:"separateMajorMinor,omitempty" yaml:"separateMajorMinor,omitempty" mapstructure:"separateMajorMinor,omitempty"`

	// If set to `true`, Renovate will separate `minor` and `patch` updates into
	// separate branches.
	SeparateMinorPatch bool `json:"separateMinorPatch,omitempty" yaml:"separateMinorPatch,omitempty" mapstructure:"separateMinorPatch,omitempty"`

	// If set to `true`, PRs will be raised separately for each available `major`
	// upgrade version.
	SeparateMultipleMajor bool `json:"separateMultipleMajor,omitempty" yaml:"separateMultipleMajor,omitempty" mapstructure:"separateMultipleMajor,omitempty"`

	// If set to `true`, Renovate creates separate PRs for each `minor` stream.
	SeparateMultipleMinor bool `json:"separateMultipleMinor,omitempty" yaml:"separateMultipleMinor,omitempty" mapstructure:"separateMultipleMinor,omitempty"`

	// Skip Renovate's automatic artifact updating.
	SkipArtifactsUpdate bool `json:"skipArtifactsUpdate,omitempty" yaml:"skipArtifactsUpdate,omitempty" mapstructure:"skipArtifactsUpdate,omitempty"`

	// Skip installing modules/dependencies if lock file updating is possible without
	// a full install.
	SkipInstalls *bool `json:"skipInstalls,omitempty" yaml:"skipInstalls,omitempty" mapstructure:"skipInstalls,omitempty"`

	// Label to make Renovate stop updating a PR.
	StopUpdatingLabel string `json:"stopUpdatingLabel,omitempty" yaml:"stopUpdatingLabel,omitempty" mapstructure:"stopUpdatingLabel,omitempty"`

	// Options to suppress various types of warnings and other notifications.
	SuppressNotifications []ConfigSuppressNotificationsElem `json:"suppressNotifications,omitempty" yaml:"suppressNotifications,omitempty" mapstructure:"suppressNotifications,omitempty"`

	// Must conform to [IANA Time
	// Zone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) format.
	Timezone *string `json:"timezone,omitempty" yaml:"timezone,omitempty" mapstructure:"timezone,omitempty"`

	// Whether to update internal dep versions in a monorepo. Works on Yarn
	// Workspaces.
	UpdateInternalDeps bool `json:"updateInternalDeps,omitempty" yaml:"updateInternalDeps,omitempty" mapstructure:"updateInternalDeps,omitempty"`

	// Whether to update branches when not scheduled. Renovate will not create
	// branches outside of the schedule.
	UpdateNotScheduled bool `json:"updateNotScheduled,omitempty" yaml:"updateNotScheduled,omitempty" mapstructure:"updateNotScheduled,omitempty"`

	// Whether to update pinned (single version) dependencies or not.
	UpdatePinnedDependencies bool `json:"updatePinnedDependencies,omitempty" yaml:"updatePinnedDependencies,omitempty" mapstructure:"updatePinnedDependencies,omitempty"`

	// Whether to read configuration from base branches instead of only the default
	// branch.
	UseBaseBranchConfig ConfigUseBaseBranchConfig `json:"useBaseBranchConfig,omitempty" yaml:"useBaseBranchConfig,omitempty" mapstructure:"useBaseBranchConfig,omitempty"`

	// User-facing strings for the Renovate comment when a PR is closed.
	UserStrings ConfigUserStrings `json:"userStrings,omitempty" yaml:"userStrings,omitempty" mapstructure:"userStrings,omitempty"`

	// A regex (`re2`) with named capture groups to show how version and compatibility
	// are split from a raw version string.
	VersionCompatibility *string `json:"versionCompatibility,omitempty" yaml:"versionCompatibility,omitempty" mapstructure:"versionCompatibility,omitempty"`

	// Versioning to use for filtering and comparisons.
	Versioning *string `json:"versioning,omitempty" yaml:"versioning,omitempty" mapstructure:"versioning,omitempty"`
}

type ConfigAutomergeStrategy string

const ConfigAutomergeStrategyAuto ConfigAutomergeStrategy = "auto"
const ConfigAutomergeStrategyFastForward ConfigAutomergeStrategy = "fast-forward"
const ConfigAutomergeStrategyMergeCommit ConfigAutomergeStrategy = "merge-commit"
const ConfigAutomergeStrategyRebase ConfigAutomergeStrategy = "rebase"
const ConfigAutomergeStrategyRebaseMerge ConfigAutomergeStrategy = "rebase-merge"
const ConfigAutomergeStrategySquash ConfigAutomergeStrategy = "squash"

type ConfigAutomergeType string

const ConfigAutomergeTypeBranch ConfigAutomergeType = "branch"
const ConfigAutomergeTypePr ConfigAutomergeType = "pr"
const ConfigAutomergeTypePrComment ConfigAutomergeType = "pr-comment"

type ConfigBumpVersion string

const ConfigBumpVersionMajor ConfigBumpVersion = "major"
const ConfigBumpVersionMinor ConfigBumpVersion = "minor"
const ConfigBumpVersionPatch ConfigBumpVersion = "patch"
const ConfigBumpVersionPrerelease ConfigBumpVersion = "prerelease"

type ConfigCommitMessageLowerCase string

const ConfigCommitMessageLowerCaseAuto ConfigCommitMessageLowerCase = "auto"
const ConfigCommitMessageLowerCaseNever ConfigCommitMessageLowerCase = "never"

// Configuration object to define language or manager version constraints.
type ConfigConstraints map[string]string

type ConfigConstraintsFiltering string

const ConfigConstraintsFilteringNone ConfigConstraintsFiltering = "none"
const ConfigConstraintsFilteringStrict ConfigConstraintsFiltering = "strict"

// Customize sections in the Dependency Dashboard issue.
type ConfigCustomizeDashboard map[string]string

type ConfigDependencyDashboardOSVVulnerabilitySummary string

const ConfigDependencyDashboardOSVVulnerabilitySummaryAll ConfigDependencyDashboardOSVVulnerabilitySummary = "all"
const ConfigDependencyDashboardOSVVulnerabilitySummaryNone ConfigDependencyDashboardOSVVulnerabilitySummary = "none"
const ConfigDependencyDashboardOSVVulnerabilitySummaryUnresolved ConfigDependencyDashboardOSVVulnerabilitySummary = "unresolved"

type ConfigFetchChangeLogs string

const ConfigFetchChangeLogsBranch ConfigFetchChangeLogs = "branch"
const ConfigFetchChangeLogsOff ConfigFetchChangeLogs = "off"
const ConfigFetchChangeLogsPr ConfigFetchChangeLogs = "pr"

type ConfigForkProcessing string

const ConfigForkProcessingAuto ConfigForkProcessing = "auto"
const ConfigForkProcessingDisabled ConfigForkProcessing = "disabled"
const ConfigForkProcessingEnabled ConfigForkProcessing = "enabled"

type ConfigInternalChecksFilter string

const ConfigInternalChecksFilterFlexible ConfigInternalChecksFilter = "flexible"
const ConfigInternalChecksFilterNone ConfigInternalChecksFilter = "none"
const ConfigInternalChecksFilterStrict ConfigInternalChecksFilter = "strict"

type ConfigMinimumReleaseAgeBehaviour string

const ConfigMinimumReleaseAgeBehaviourTimestampOptional ConfigMinimumReleaseAgeBehaviour = "timestamp-optional"
const ConfigMinimumReleaseAgeBehaviourTimestampRequired ConfigMinimumReleaseAgeBehaviour = "timestamp-required"

type ConfigMode string

const ConfigModeFull ConfigMode = "full"
const ConfigModeSilent ConfigMode = "silent"

type ConfigPlatformCommit string

const ConfigPlatformCommitAuto ConfigPlatformCommit = "auto"
const ConfigPlatformCommitDisabled ConfigPlatformCommit = "disabled"
const ConfigPlatformCommitEnabled ConfigPlatformCommit = "enabled"

type ConfigPostUpdateOptionsElem string

const ConfigPostUpdateOptionsElemBundlerConservative ConfigPostUpdateOptionsElem = "bundlerConservative"
const ConfigPostUpdateOptionsElemComposerNoMinimalChanges ConfigPostUpdateOptionsElem = "composerNoMinimalChanges"
const ConfigPostUpdateOptionsElemComposerWithAll ConfigPostUpdateOptionsElem = "composerWithAll"
const ConfigPostUpdateOptionsElemDotnetWorkloadRestore ConfigPostUpdateOptionsElem = "dotnetWorkloadRestore"
const ConfigPostUpdateOptionsElemGoGenerate ConfigPostUpdateOptionsElem = "goGenerate"
const ConfigPostUpdateOptionsElemGomodMassage ConfigPostUpdateOptionsElem = "gomodMassage"
const ConfigPostUpdateOptionsElemGomodSkipVendor ConfigPostUpdateOptionsElem = "gomodSkipVendor"
const ConfigPostUpdateOptionsElemGomodTidy ConfigPostUpdateOptionsElem = "gomodTidy"
const ConfigPostUpdateOptionsElemGomodTidy117 ConfigPostUpdateOptionsElem = "gomodTidy1.17"
const ConfigPostUpdateOptionsElemGomodTidyE ConfigPostUpdateOptionsElem = "gomodTidyE"
const ConfigPostUpdateOptionsElemGomodUpdateImportPaths ConfigPostUpdateOptionsElem = "gomodUpdateImportPaths"
const ConfigPostUpdateOptionsElemGomodVendor ConfigPostUpdateOptionsElem = "gomodVendor"
const ConfigPostUpdateOptionsElemHelmUpdateSubChartArchives ConfigPostUpdateOptionsElem = "helmUpdateSubChartArchives"
const ConfigPostUpdateOptionsElemKustomizeInflateHelmCharts ConfigPostUpdateOptionsElem = "kustomizeInflateHelmCharts"
const ConfigPostUpdateOptionsElemNpmDedupe ConfigPostUpdateOptionsElem = "npmDedupe"
const ConfigPostUpdateOptionsElemNpmInstallTwice ConfigPostUpdateOptionsElem = "npmInstallTwice"
const ConfigPostUpdateOptionsElemPnpmDedupe ConfigPostUpdateOptionsElem = "pnpmDedupe"
const ConfigPostUpdateOptionsElemYarnDedupeFewer ConfigPostUpdateOptionsElem = "yarnDedupeFewer"
const ConfigPostUpdateOptionsElemYarnDedupeHighest ConfigPostUpdateOptionsElem = "yarnDedupeHighest"

// Table column definitions to use in PR tables.
type ConfigPrBodyDefinitions map[string]interface{}

// Table header definitions to use in PR tables.
type ConfigPrBodyHeadingDefinitions map[string]interface{}

type ConfigPrCreation string

const ConfigPrCreationApproval ConfigPrCreation = "approval"
const ConfigPrCreationImmediate ConfigPrCreation = "immediate"
const ConfigPrCreationNotPending ConfigPrCreation = "not-pending"
const ConfigPrCreationStatusSuccess ConfigPrCreation = "status-success"

type ConfigRangeStrategy string

const ConfigRangeStrategyAuto ConfigRangeStrategy = "auto"
const ConfigRangeStrategyBump ConfigRangeStrategy = "bump"
const ConfigRangeStrategyInRangeOnly ConfigRangeStrategy = "in-range-only"
const ConfigRangeStrategyPin ConfigRangeStrategy = "pin"
const ConfigRangeStrategyReplace ConfigRangeStrategy = "replace"
const ConfigRangeStrategyUpdateLockfile ConfigRangeStrategy = "update-lockfile"
const ConfigRangeStrategyWiden ConfigRangeStrategy = "widen"

type ConfigRebaseWhen string

const ConfigRebaseWhenAuto ConfigRebaseWhen = "auto"
const ConfigRebaseWhenAutomerging ConfigRebaseWhen = "automerging"
const ConfigRebaseWhenBehindBaseBranch ConfigRebaseWhen = "behind-base-branch"
const ConfigRebaseWhenConflicted ConfigRebaseWhen = "conflicted"
const ConfigRebaseWhenNever ConfigRebaseWhen = "never"

type ConfigRecreateWhen string

const ConfigRecreateWhenAlways ConfigRecreateWhen = "always"
const ConfigRecreateWhenAuto ConfigRecreateWhen = "auto"
const ConfigRecreateWhenNever ConfigRecreateWhen = "never"

type ConfigReplacementApproach string

const ConfigReplacementApproachAlias ConfigReplacementApproach = "alias"
const ConfigReplacementApproachReplace ConfigReplacementApproach = "replace"

type ConfigSemanticCommits string

const ConfigSemanticCommitsAuto ConfigSemanticCommits = "auto"
const ConfigSemanticCommitsDisabled ConfigSemanticCommits = "disabled"
const ConfigSemanticCommitsEnabled ConfigSemanticCommits = "enabled"

type ConfigSuppressNotificationsElem string

const ConfigSuppressNotificationsElemArtifactErrors ConfigSuppressNotificationsElem = "artifactErrors"
const ConfigSuppressNotificationsElemBranchAutomergeFailure ConfigSuppressNotificationsElem = "branchAutomergeFailure"
const ConfigSuppressNotificationsElemConfigErrorIssue ConfigSuppressNotificationsElem = "configErrorIssue"
const ConfigSuppressNotificationsElemDependencyLookupWarnings ConfigSuppressNotificationsElem = "dependencyLookupWarnings"
const ConfigSuppressNotificationsElemLockFileErrors ConfigSuppressNotificationsElem = "lockFileErrors"
const ConfigSuppressNotificationsElemMissingCredentialsError ConfigSuppressNotificationsElem = "missingCredentialsError"
const ConfigSuppressNotificationsElemOnboardingClose ConfigSuppressNotificationsElem = "onboardingClose"
const ConfigSuppressNotificationsElemPrEditedNotification ConfigSuppressNotificationsElem = "prEditedNotification"
const ConfigSuppressNotificationsElemPrIgnoreNotification ConfigSuppressNotificationsElem = "prIgnoreNotification"

type ConfigUseBaseBranchConfig string

const ConfigUseBaseBranchConfigMerge ConfigUseBaseBranchConfig = "merge"
const ConfigUseBaseBranchConfigNone ConfigUseBaseBranchConfig = "none"

// User-facing strings for the Renovate comment when a PR is closed.
type ConfigUserStrings map[string]interface{}
