name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix develop -c make test

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check --all-systems
      - run: nix build

  gomod2nix:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix develop -c go tool gomod2nix
      - run: git diff --exit-code gomod2nix.toml

  clean:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: unstoppablemango
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix develop -c make pkg/renovate/zz_generated.schema.go
      - run: git diff --exit-code
